<?php

declare(strict_types=1);

namespace Semitexa\Ssr\Tests\Unit\Seo;

require_once __DIR__ . '/Fixture/SitemapTestKit.php';
require_once __DIR__ . '/Fixture/OversizedSitemapProvider.php';
require_once __DIR__ . '/Fixture/CountingSitemapProvider.php';

use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use Semitexa\Core\Http\Response\ResourceResponse;
use Semitexa\Core\Request;
use Semitexa\Core\Support\ProjectRoot;
use Semitexa\Ssr\Application\Handler\PayloadHandler\SitemapPartHandler;
use Semitexa\Ssr\Application\Handler\PayloadHandler\SitemapXmlHandler;
use Semitexa\Ssr\Application\Payload\Request\SitemapPartPayload;
use Semitexa\Ssr\Application\Payload\Request\SitemapXmlPayload;
use Semitexa\Ssr\Application\Service\Seo\Sitemap\GeneratedSitemapCache;
use Semitexa\Ssr\Application\Service\Seo\Sitemap\SitemapGenerator;
use Semitexa\Ssr\Application\Service\Seo\Sitemap\SitemapStoragePath;
use Semitexa\Ssr\Tests\Unit\Seo\Fixture\CountingSitemapProvider;
use Semitexa\Ssr\Tests\Unit\Seo\Fixture\OversizedSitemapProvider;
use Semitexa\Ssr\Tests\Unit\Seo\Fixture\SitemapTestKit;
use Semitexa\Tenancy\Context\TenantContext;

/**
 * A generated sitemap is a cache with a maximum age.
 *
 * MEASURED on production: sitemap.xml was served from a file generated in April
 * and never refreshed — the install has no scheduler, so the regeneration job
 * never ran — advertising ~95 URLs of another tenant that 404 on the domain.
 */
final class GeneratedSitemapCacheTest extends TestCase
{
    private const string STALE_MARKER = 'https://other-tenant.test/from-april';

    private string $originalCwd;
    private string $root;
    private string|false $originalTtl;

    protected function setUp(): void
    {
        $this->originalCwd = getcwd() ?: sys_get_temp_dir();
        $this->originalTtl = getenv('SITEMAP_CACHE_TTL');
        putenv('SITEMAP_CACHE_TTL');

        $this->root = sys_get_temp_dir() . '/semitexa-sitemap-cache-' . uniqid('', true);
        mkdir($this->root . '/src/modules', 0777, true);
        mkdir($this->root . '/public', 0777, true);
        file_put_contents($this->root . '/composer.json', '{}');

        chdir($this->root);
        ProjectRoot::reset();
    }

    protected function tearDown(): void
    {
        chdir($this->originalCwd);
        ProjectRoot::reset();
        $this->originalTtl === false ? putenv('SITEMAP_CACHE_TTL') : putenv('SITEMAP_CACHE_TTL=' . $this->originalTtl);
        exec('rm -rf ' . escapeshellarg($this->root));
    }

    #[Test]
    public function a_generated_file_older_than_a_day_is_regenerated_not_served(): void
    {
        $path = $this->writeGenerated(age: 86_400 + 60);

        $served = $this->serve();

        self::assertStringNotContainsString(self::STALE_MARKER, $served, 'a months-old cache was served as the sitemap');
        self::assertStringContainsString('<urlset', $served);
        self::assertStringNotContainsString(self::STALE_MARKER, (string) file_get_contents($path), 'the regenerated sitemap must replace the stale file');
    }

    #[Test]
    public function a_fresh_generated_file_is_served_as_is(): void
    {
        $this->writeGenerated(age: 60);

        self::assertStringContainsString(self::STALE_MARKER, $this->serve());
    }

    /**
     * MEASURED on semitexa.com, 2026-09-27 and again 2026-09-28: auto-deploy
     * installed a site release whose sitemap lists every article, and
     * /sitemap.xml kept serving the 4 URLs the previous code had written the day
     * before — inside the TTL, and on disk, so no restart helped. Twice the
     * cache was moved aside by hand. An index written by other code is stale.
     */
    #[Test]
    public function an_index_written_by_other_code_is_regenerated(): void
    {
        $path = $this->writeGenerated(age: 60, codeStamp: 'the-previous-release');

        $response = $this->serveResponse();

        self::assertSame(200, $response->getStatusCode());
        self::assertStringStartsWith('<?xml', (string) $response->getContent());
        self::assertStringNotContainsString(self::STALE_MARKER, (string) $response->getContent());
        self::assertStringStartsWith('<?xml', (string) file_get_contents($path), 'the regenerated index must replace the old file');
        self::assertStringContainsString('<!-- semitexa-code: ' . GeneratedSitemapCache::codeIdentity() . ' -->', (string) file_get_contents($path));
    }

    /** An index from before stamps existed is the first deploy after this change: regenerate once. */
    #[Test]
    public function an_index_without_a_code_stamp_is_regenerated(): void
    {
        $path = $this->writeGenerated(age: 60, codeStamp: null);

        $this->serve();

        self::assertStringContainsString('<!-- semitexa-code: ' . GeneratedSitemapCache::codeIdentity() . ' -->', (string) file_get_contents($path));
    }

    /**
     * The index decides for its parts. A deploy makes the index stale, so the
     * advertised part is regenerated by the new code — and served, not 404.
     */
    #[Test]
    public function a_part_behind_an_index_from_other_code_is_regenerated_and_served(): void
    {
        $dir = dirname($this->writeGenerated(age: 60, codeStamp: 'the-previous-release'));
        file_put_contents($dir . '/sitemap-1.xml', '<urlset><!-- old part --></urlset>');

        $response = $this->servePart('1', SitemapTestKit::generator([OversizedSitemapProvider::class]));

        self::assertSame(200, $response->getStatusCode());
        self::assertStringContainsString('/item/1</loc>', (string) $response->getContent());
        self::assertStringNotContainsString('old part', (string) $response->getContent());
    }

    /**
     * Reviewed on ssr#135: a part written a moment before a deploy, behind an
     * index the new code wrote, must still be served — a part has no stamp
     * and is never judged apart from its index.
     */
    #[Test]
    public function a_part_behind_an_index_from_this_code_is_served_whenever_it_was_written(): void
    {
        $dir = dirname($this->writeGenerated(age: 60));
        file_put_contents($dir . '/sitemap-1.xml', '<urlset><!-- part one --></urlset>');
        touch($dir . '/sitemap-1.xml', time() - 3_600);

        $response = $this->servePart('1', new SitemapGenerator());

        self::assertSame(200, $response->getStatusCode());
        self::assertSame('<urlset><!-- part one --></urlset>', $response->getContent());
    }

    /**
     * Reviewed on ssr#135: with the identity in a second file, an old-release
     * worker's index could land between a new worker's index and its stamp and
     * be vouched for. The identity now travels inside the index, one rename.
     */
    #[Test]
    public function the_written_index_carries_its_own_identity_and_nothing_else_does(): void
    {
        $dir = SitemapStoragePath::generatedDirectory($this->tenant());
        $written = SitemapTestKit::generator([OversizedSitemapProvider::class]);
        $written->write($written->generate(new \Semitexa\Ssr\Application\Service\Seo\Sitemap\SitemapGenerationContext(
            baseUrl: 'https://museum.test',
            tenantContext: $this->tenant(),
        )), $dir);

        self::assertNotNull(GeneratedSitemapCache::readFreshIndex($dir));
        self::assertNull(GeneratedSitemapCache::readFreshIndex($dir, codeIdentity: str_repeat('0', 64)));
        self::assertSame(['sitemap-1.xml', 'sitemap-2.xml', 'sitemap.xml'], array_values(array_filter(
            scandir($dir) ?: [],
            static fn (string $f): bool => $f[0] !== '.',
        )));
    }

    #[Test]
    public function a_stamp_follows_the_xml_declaration(): void
    {
        self::assertSame(
            '<?xml version="1.0"?>' . "\n" . '<!-- semitexa-code: abc -->' . "\n" . '<urlset/>',
            GeneratedSitemapCache::stamp('<?xml version="1.0"?>' . "\n" . '<urlset/>', 'abc'),
        );
    }

    #[Test]
    public function the_max_age_comes_from_sitemap_cache_ttl(): void
    {
        $this->writeGenerated(age: 600);

        putenv('SITEMAP_CACHE_TTL=3600');
        self::assertStringContainsString(self::STALE_MARKER, $this->serve());

        putenv('SITEMAP_CACHE_TTL=300');
        self::assertStringNotContainsString(self::STALE_MARKER, $this->serve());
    }

    #[Test]
    public function a_manual_override_still_wins_over_regeneration(): void
    {
        $this->writeGenerated(age: 86_400 * 150);
        file_put_contents($this->root . '/public/sitemap.xml', '<urlset><!-- hand written --></urlset>');

        self::assertStringContainsString('hand written', $this->serve());
    }

    /**
     * The scheduler may own var/sitemap under another user. A request that
     * regenerated the sitemap must still serve it when it cannot persist it.
     */
    #[Test]
    public function an_unwritable_cache_still_serves_the_regenerated_sitemap(): void
    {
        $dir = SitemapStoragePath::generatedDirectory($this->tenant());
        // A directory where sitemap.xml should be: no write can replace it, even as root.
        mkdir($dir . '/sitemap.xml', 0777, true);

        $response = $this->serveResponse();

        self::assertSame(200, $response->getStatusCode());
        self::assertSame(
            '<?xml version="1.0" encoding="UTF-8"?>' . "\n" . '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml"/>' . "\n",
            $response->getContent(),
        );
    }

    /**
     * A refresh replaces the file, never rewrites it in place: a request still
     * reading the old sitemap keeps reading the old, complete bytes.
     */
    #[Test]
    public function a_refresh_replaces_the_file_instead_of_rewriting_it_in_place(): void
    {
        $path = $this->writeGenerated(age: 86_400 + 60);
        $before = (string) file_get_contents($path);
        $heldByAReader = $this->root . '/held-by-a-reader.xml';
        link($path, $heldByAReader);

        $this->serve();

        self::assertSame($before, (string) file_get_contents($heldByAReader), 'the old file was truncated and rewritten under a reader');
        self::assertStringNotContainsString(self::STALE_MARKER, (string) file_get_contents($path));
        self::assertSame([], glob(dirname($path) . '/*.tmp.*') ?: [], 'no temporary file may be left behind');
    }

    /**
     * Parts are written just before their index, so near the TTL boundary a
     * part is a moment older than the fresh index that links to it.
     */
    #[Test]
    public function a_part_linked_from_a_fresh_index_is_served_whatever_its_own_age(): void
    {
        $dir = dirname($this->writeGenerated(age: 60));
        $part = $dir . '/sitemap-1.xml';
        file_put_contents($part, '<urlset><!-- part one --></urlset>');
        touch($part, time() - 86_400 - 60);

        $handler = new SitemapPartHandler();
        SitemapTestKit::set($handler, 'request', new Request('GET', '/sitemap-1.xml', ['Host' => 'museum.test'], [], [], ['HTTP_HOST' => 'museum.test'], []));
        SitemapTestKit::set($handler, 'tenantContext', $this->tenant());
        SitemapTestKit::set($handler, 'generator', new SitemapGenerator());
        $payload = new SitemapPartPayload();
        $payload->part = '1';

        $response = $handler->handle($payload, new ResourceResponse());

        self::assertSame(200, $response->getStatusCode());
        self::assertSame('<urlset><!-- part one --></urlset>', $response->getContent());
    }

    /**
     * An unwritable sitemap directory still serves an index generated in
     * memory; its parts must be served the same way instead of 404ing.
     */
    #[Test]
    public function a_part_is_served_from_memory_when_the_directory_cannot_be_written(): void
    {
        $dir = SitemapStoragePath::generatedDirectory($this->tenant());
        mkdir(dirname($dir), 0777, true);
        file_put_contents($dir, 'not a directory'); // mkdir and every write under it fail, even as root

        $handler = new SitemapPartHandler();
        SitemapTestKit::set($handler, 'request', new Request('GET', '/sitemap-2.xml', ['Host' => 'museum.test'], [], [], ['HTTP_HOST' => 'museum.test'], []));
        SitemapTestKit::set($handler, 'tenantContext', $this->tenant());
        SitemapTestKit::set($handler, 'generator', SitemapTestKit::generator([OversizedSitemapProvider::class]));
        $payload = new SitemapPartPayload();
        $payload->part = '2';

        $response = $handler->handle($payload, new ResourceResponse());

        self::assertSame(200, $response->getStatusCode());
        self::assertStringContainsString('/item/' . OversizedSitemapProvider::COUNT . '</loc>', (string) $response->getContent());
    }

    /** A part name the generator never produces must not trigger a regeneration. */
    #[Test]
    public function an_unknown_part_name_does_not_regenerate(): void
    {
        $dir = SitemapStoragePath::generatedDirectory($this->tenant());
        mkdir(dirname($dir), 0777, true);
        file_put_contents($dir, 'not a directory');

        $handler = new SitemapPartHandler();
        SitemapTestKit::set($handler, 'request', new Request('GET', '/sitemap-news.xml', ['Host' => 'museum.test'], [], [], ['HTTP_HOST' => 'museum.test'], []));
        SitemapTestKit::set($handler, 'tenantContext', $this->tenant());
        SitemapTestKit::set($handler, 'generator', SitemapTestKit::generator([CountingSitemapProvider::class]));
        $payload = new SitemapPartPayload();
        $payload->part = 'news';

        $before = CountingSitemapProvider::$calls;
        CountingSitemapProvider::$calls = 0;
        try {
            $response = $handler->handle($payload, new ResourceResponse());
            $calls = CountingSitemapProvider::$calls;
        } finally {
            CountingSitemapProvider::$calls = $before;
        }

        self::assertSame(404, $response->getStatusCode());
        self::assertSame(0, $calls, 'an unknown part name ran the generator');
    }

    /**
     * @param string|false|null $codeStamp false = stamped by the code running this test; null = no stamp
     */
    private function writeGenerated(int $age, string|false|null $codeStamp = false): string
    {
        $dir = SitemapStoragePath::generatedDirectory($this->tenant());
        mkdir($dir, 0777, true);
        $path = $dir . '/sitemap.xml';
        file_put_contents($path, '<urlset><url><loc>' . self::STALE_MARKER . '</loc></url></urlset>');
        touch($path, time() - $age);
        if ($codeStamp !== null) {
            $xml = (string) file_get_contents($path);
            file_put_contents($path, GeneratedSitemapCache::stamp($xml, $codeStamp === false ? (string) GeneratedSitemapCache::codeIdentity() : $codeStamp));
            touch($path, time() - $age);
        }

        return $path;
    }

    private function servePart(string $part, SitemapGenerator $generator): ResourceResponse
    {
        $handler = new SitemapPartHandler();
        SitemapTestKit::set($handler, 'request', new Request('GET', '/sitemap-' . $part . '.xml', ['Host' => 'museum.test'], [], [], ['HTTP_HOST' => 'museum.test'], []));
        SitemapTestKit::set($handler, 'tenantContext', $this->tenant());
        SitemapTestKit::set($handler, 'generator', $generator);
        $payload = new SitemapPartPayload();
        $payload->part = $part;

        return $handler->handle($payload, new ResourceResponse());
    }

    private function serve(): string
    {
        return (string) $this->serveResponse()->getContent();
    }

    private function serveResponse(): ResourceResponse
    {
        $handler = new SitemapXmlHandler();
        SitemapTestKit::set($handler, 'request', new Request('GET', '/sitemap.xml', ['Host' => 'museum.test'], [], [], ['HTTP_HOST' => 'museum.test'], []));
        SitemapTestKit::set($handler, 'tenantContext', $this->tenant());
        SitemapTestKit::set($handler, 'generator', new SitemapGenerator());

        return $handler->handle(new SitemapXmlPayload(), new ResourceResponse());
    }

    private function tenant(): TenantContext
    {
        return TenantContext::fromResolution('museum', 'test');
    }
}
